import { Category, Game, Item, PaymentMethod, PromoCode, Transaction } from "@/db/schema";

export const initialCategories: Category[] = [
  { id: "cat-mobile", name: "Mobile Games", slug: "mobile-games", icon: "Smartphone", createdAt: new Date() },
  { id: "cat-pc", name: "PC Games", slug: "pc-games", icon: "Monitor", createdAt: new Date() },
  { id: "cat-voucher", name: "Voucher & Gift Card", slug: "voucher", icon: "Gift", createdAt: new Date() },
  { id: "cat-app", name: "Entertainment / Apps", slug: "apps", icon: "Tv", createdAt: new Date() },
];

export const initialGames: Game[] = [
    {
      id: "game-mlbb",
      name: "Mobile Legends: Bang Bang",
      slug: "mobile-legends",
      categoryId: "cat-mobile",
      developer: "Moonton",
      description: "Top up Diamond Mobile Legends resmi, cepat, dan murah. Proses instan 1-3 detik langsung masuk ke akun Mobile Legends kamu.",
      thumbnailUrl: "/images/games/mlbb.png",
      bannerUrl: "/images/banner/mlbb.png",
      accountInputs: {
        userId: true,
        userLabel: "User ID",
        userPlaceholder: "Contoh: 123456789",
        zoneId: true,
        zoneLabel: "Zone ID",
        zonePlaceholder: "Contoh: 2105",
        helperText: "Untuk mengetahui User ID Anda, buka profil game di pojok kiri atas. User ID tertera di bawah foto profil (format: 123456789 (2105)).",
      },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ff",
      name: "Free Fire",
      slug: "free-fire",
      categoryId: "cat-mobile",
      developer: "Garena",
      description: "Beli Diamond Free Fire murah & instan. Dukung push rank Booyah kamu sekarang juga tanpa ribet!",
      thumbnailUrl: "/images/games/ff.png",
      bannerUrl: "/images/banner/ff.png",
      accountInputs: {
        userId: true,
        userLabel: "Player ID",
        userPlaceholder: "Contoh: 87654321",
        helperText: "Untuk mengetahui Player ID Anda, klik avatar Anda di sudut kiri atas layar utama Free Fire.",
      },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-genshin",
      name: "Genshin Impact",
      slug: "genshin-impact",
      categoryId: "cat-mobile",
      developer: "HoYoverse",
      description: "Top up Genesis Crystals & Blessing of the Welkin Moon resmi melalui HoYoverse UID. Instan dan aman 100%.",
      thumbnailUrl: "/images/games/genshin-impact.png",
      bannerUrl: "/images/banner/genshin-impact.png",
      accountInputs: {
        userId: true,
        userLabel: "UID Genshin Impact",
        userPlaceholder: "Contoh: 801234567",
        serverList: [
          { label: "Asia", value: "os_asia" },
          { label: "America", value: "os_usa" },
          { label: "Europe", value: "os_euro" },
          { label: "TW, HK, MO", value: "os_cht" },
        ],
        helperText: "UID dapat dilihat pada pojok kanan bawah layar game atau di menu Paimon.",
      },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-valorant",
      name: "Valorant",
      slug: "valorant",
      categoryId: "cat-pc",
      developer: "Riot Games",
      description: "Beli Valorant Points (VP) resmi Riot Games Indonesia. Buka Skin Vandal & Phantom idamanmu sekarang!",
      thumbnailUrl: "/images/games/valorant.png",
      bannerUrl: "/images/banner/valorant.png",
      accountInputs: {
        userId: true,
        userLabel: "Riot ID",
        userPlaceholder: "Contoh: Player#ID1",
        helperText: "Masukkan Riot ID lengkap beserta Tagline (#TAG).",
      },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-codm",
      name: "Call of Duty: Mobile",
      slug: "call-of-duty-mobile",
      categoryId: "cat-mobile",
      developer: "Activision",
      description: "Top up CP (Call of Duty Points) resmi untuk Call of Duty Mobile. Dapatkan skin senjata, karakter, dan Battle Pass eksklusif.",
      thumbnailUrl: "/images/games/codm.png",
      bannerUrl: "/images/banner/codm.png",
      accountInputs: {
        userId: true,
        userLabel: "Player ID",
        userPlaceholder: "Contoh: 8765432109",
        helperText: "Masukkan Player ID lengkap (angka saja, tanpa simbol).",
      },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-roblox",
      name: "Roblox",
      slug: "roblox",
      categoryId: "cat-mobile",
      developer: "Roblox Corporation",
      description: "Beli Robux resmi Roblox. Gunakan Robux untuk membeli item avatar, akses premium, dan fitur eksklusif di Roblox.",
      thumbnailUrl: "/images/games/roblox.png",
      bannerUrl: "/images/banner/roblox.png",
      accountInputs: {
        userId: true,
        userLabel: "Username Roblox",
        userPlaceholder: "Contoh: PlayerName123",
        helperText: "Masukkan username Roblox Anda (bukan display name).",
      },
      hasServerCheck: false,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-afk-journey",
      name: "AFK Journey",
      slug: "afk-journey",
      categoryId: "cat-mobile",
      developer: "Lilith Games",
      description: "Top up Crystals dan Diamond AFK Journey resmi dan instan.",
      thumbnailUrl: "/images/games/afk-journey.png",
      bannerUrl: "/images/banner/afk-journey.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID AFK Journey Anda." },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },

    {
      id: "game-pubg-ns",
      name: "PUBG New State",
      slug: "pubg-new-state",
      categoryId: "cat-mobile",
      developer: "Krafton",
      description: "Top up NC (New State Cash) PUBG New State resmi dan termurah.",
      thumbnailUrl: "/images/games/pubg-new-state.png",
      bannerUrl: "/images/banner/pubg-new-state.png",
      accountInputs: { userId: true, userLabel: "Player ID", userPlaceholder: "Contoh: 987654321", helperText: "ID PUBG New State Anda." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-hok",
      name: "Honor of Kings",
      slug: "honor-of-kings",
      categoryId: "cat-mobile",
      developer: "Tencent",
      description: "Top up Token Honor of Kings resmi dan instan.",
      thumbnailUrl: "/images/games/hok.png",
      bannerUrl: "/images/banner/hok.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Honor of Kings." },
      hasServerCheck: true,
      isPopular: true,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-lol-wr",
      name: "League of Legends: Wild Rift",
      slug: "lol-wild-rift",
      categoryId: "cat-mobile",
      developer: "Riot Games",
      description: "Top up Wild Cores Wild Rift resmi.",
      thumbnailUrl: "/images/games/wild-rift.png",
      bannerUrl: "/images/banner/wild-rift.png",
      accountInputs: { userId: true, userLabel: "Riot ID", userPlaceholder: "Contoh: Player#ID", helperText: "Masukkan Riot ID lengkap." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-honkai",
      name: "Honkai Star Rail",
      slug: "honkai-star-rail",
      categoryId: "cat-mobile",
      developer: "HoYoverse",
      description: "Top up Crystals Honkai Star Rail resmi.",
      thumbnailUrl: "/images/games/hsr.png",
      bannerUrl: "/images/banner/hsr.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 801234567", serverList: [{label:"Asia",value:"os_asia"}], helperText: "UID Honkai Star Rail." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-zenless",
      name: "Zenless Zone Zero",
      slug: "zenless-zone-zero",
      categoryId: "cat-mobile",
      developer: "HoYoverse",
      description: "Top up Monochrome Zenless Zone Zero resmi.",
      thumbnailUrl: "/images/games/zzz.png",
      bannerUrl: "/images/banner/zzz.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 801234567", serverList: [{label:"Asia",value:"os_asia"}], helperText: "UID ZZZ." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-delta",
      name: "Delta Force",
      slug: "delta-force",
      categoryId: "cat-pc",
      developer: "Level Infinite",
      description: "Top up Delta Coins Delta Force resmi.",
      thumbnailUrl: "/images/games/delta-force.png",
      bannerUrl: "/images/banner/delta-force.png",
      accountInputs: { userId: true, userLabel: "Player ID", userPlaceholder: "Contoh: 987654321", helperText: "Player ID Delta Force." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-pubgm",
      name: "PUBG Mobile",
      slug: "pubg-mobile",
      categoryId: "cat-mobile",
      developer: "Level Infinite",
      description: "Top up UC PUBG Mobile resmi dan termurah. Buka Royale Pass dan upgrade skin senjata eksklusif.",
      thumbnailUrl: "/images/games/pubgm.png",
      bannerUrl: "/images/banner/pubgm.png",
      accountInputs: {
        userId: true,
        userLabel: "Player ID",
        userPlaceholder: "Contoh: 512345678",
        helperText: "Buka profil di pojok kiri atas lobi, ID tertera di bawah nama akun.",
      },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-steam",
      name: "Steam Wallet Code (IDR)",
      slug: "steam-wallet",
      categoryId: "cat-voucher",
      developer: "Valve",
      description: "Beli Voucher Steam Wallet Rupiah resmi. Kode voucher langsung dikirimkan ke WhatsApp & Email kamu.",
      thumbnailUrl: "/images/games/steam.png",
      bannerUrl: "/images/banner/steam.png",
      accountInputs: {
        userId: true,
        userLabel: "Nomor WhatsApp / Akun",
        userPlaceholder: "Contoh: 081234567890",
        helperText: "Kode voucher akan dikirimkan otomatis ke kontak WhatsApp Anda.",
      },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ace-racer",
      name: "Ace Racer",
      slug: "ace-racer",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Speed Up Ace Racer resmi dan instan.",
      thumbnailUrl: "/images/games/ace-racer.png",
      bannerUrl: "/images/banner/ace-racer.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Ace Racer Anda." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-age-of-empires-mobile",
      name: "Age of Empires Mobile",
      slug: "age-of-empires-mobile",
      categoryId: "cat-mobile",
      developer: "TiMi Studio Group",
      description: "Top up Age of Empires Mobile resmi dan instan.",
      thumbnailUrl: "/images/games/age-of-empires.png",
      bannerUrl: "/images/banner/age-of-empires.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Age of Empires Mobile." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-arena-breakout",
      name: "Arena Breakout",
      slug: "arena-breakout",
      categoryId: "cat-mobile",
      developer: "Morefun Studios",
      description: "Top up Koen Arena Breakout resmi dan instan.",
      thumbnailUrl: "/images/games/arena-breakout.png",
      bannerUrl: "/images/banner/arena-breakout.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Arena Breakout." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-arena-breakout-infinite",
      name: "Arena Breakout: Infinite",
      slug: "arena-breakout-infinite",
      categoryId: "cat-pc",
      developer: "Morefun Studios",
      description: "Top up Arena Breakout: Infinite PC resmi dan instan.",
      thumbnailUrl: "/images/games/arena-breakout-infinite.png",
      bannerUrl: "/images/banner/arena-breakout-infinite.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Arena Breakout: Infinite." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-arena-of-valor",
      name: "Arena of Valor",
      slug: "arena-of-valor",
      categoryId: "cat-mobile",
      developer: "Tencent Games",
      description: "Top up Voucher Arena of Valor resmi dan instan.",
      thumbnailUrl: "/images/games/aov.png",
      bannerUrl: "/images/banner/aov.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Arena of Valor." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-astral-guardians",
      name: "Astral Guardians: Cyber Fantasy",
      slug: "astral-guardians",
      categoryId: "cat-mobile",
      developer: "XD Entertainment",
      description: "Top up Astral Guardians: Cyber Fantasy resmi dan instan.",
      thumbnailUrl: "/images/games/astral-guardians.png",
      bannerUrl: "/images/banner/astral-guardians.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Astral Guardians." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-be-the-king",
      name: "Be The King",
      slug: "be-the-king",
      categoryId: "cat-mobile",
      developer: "Wish Interactive",
      description: "Top up Be The King resmi dan instan.",
      thumbnailUrl: "/images/games/be-the-king.png",
      bannerUrl: "/images/banner/be-the-king.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Be The King." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-blood-strike",
      name: "Blood Strike",
      slug: "blood-strike",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Blood Strike resmi dan instan.",
      thumbnailUrl: "/images/games/blood-strike.png",
      bannerUrl: "/images/banner/blood-strike.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Blood Strike." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-castle-duels",
      name: "Castle Duels",
      slug: "castle-duels",
      categoryId: "cat-mobile",
      developer: "Miniclip",
      description: "Top up Castle Duels resmi dan instan.",
      thumbnailUrl: "/images/games/castle-duels.png",
      bannerUrl: "/images/banner/castle-duels.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Castle Duels." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-dragon-raja",
      name: "Dragon Raja",
      slug: "dragon-raja",
      categoryId: "cat-mobile",
      developer: "Tencent Games",
      description: "Top up Dragon Raja resmi dan instan.",
      thumbnailUrl: "/images/games/dragon-raja.png",
      bannerUrl: "/images/banner/dragon-raja.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Dragon Raja." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-dragonheir",
      name: "Dragonheir: Silent Gods",
      slug: "dragonheir",
      categoryId: "cat-mobile",
      developer: "Tencent Games",
      description: "Top up Dragonheir: Silent Gods resmi dan instan.",
      thumbnailUrl: "/images/games/dragonheir.png",
      bannerUrl: "/images/banner/dragonheir.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Dragonheir." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-dynasty-heroes",
      name: "Dynasty Heroes",
      slug: "dynasty-heroes",
      categoryId: "cat-mobile",
      developer: "Youzu Interactive",
      description: "Top up Dynasty Heroes resmi dan instan.",
      thumbnailUrl: "/images/games/dynasty-heroes.png",
      bannerUrl: "/images/banner/dynasty-heroes.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Dynasty Heroes." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-dynasty-warriors-overlords",
      name: "Dynasty Warriors: Overlords",
      slug: "dynasty-warriors-overlords",
      categoryId: "cat-mobile",
      developer: "KOEI TECMO Games",
      description: "Top up Dynasty Warriors: Overlords resmi dan instan.",
      thumbnailUrl: "/images/games/dynasty-warriors-overlords.png",
      bannerUrl: "/images/banner/dynasty-warriors-overlords.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Dynasty Warriors: Overlords." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ea-sports-fc-mobile",
      name: "EA SPORTS FC Mobile",
      slug: "ea-sports-fc-mobile",
      categoryId: "cat-mobile",
      developer: "Electronic Arts",
      description: "Top up FIFA Points EA SPORTS FC Mobile resmi dan instan.",
      thumbnailUrl: "/images/games/fc-mobile.png",
      bannerUrl: "/images/banner/fc-mobile.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID EA SPORTS FC Mobile." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-eggy-party",
      name: "Eggy Party",
      slug: "eggy-party",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Eggy Party resmi dan instan.",
      thumbnailUrl: "/images/games/eggy-party.png",
      bannerUrl: "/images/banner/eggy-party.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Eggy Party." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-farlight-84",
      name: "Farlight 84",
      slug: "farlight-84",
      categoryId: "cat-mobile",
      developer: "Lilith Games",
      description: "Top up Farlight 84 resmi dan instan.",
      thumbnailUrl: "/images/games/farlight-84.png",
      bannerUrl: "/images/banner/farlight-84.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Farlight 84." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-football-master-2",
      name: "Football Master 2",
      slug: "football-master-2",
      categoryId: "cat-mobile",
      developer: "Game Hollywood",
      description: "Top up Football Master 2 resmi dan instan.",
      thumbnailUrl: "/images/games/football-master-2.png",
      bannerUrl: "/images/banner/football-master-2.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Football Master 2." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-garena-undawn",
      name: "Garena Undawn",
      slug: "garena-undawn",
      categoryId: "cat-mobile",
      developer: "Tencent Games",
      description: "Top up Garena Undawn resmi dan instan.",
      thumbnailUrl: "/images/games/undawn.png",
      bannerUrl: "/images/banner/undawn.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Garena Undawn." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-growtopia",
      name: "Growtopia",
      slug: "growtopia",
      categoryId: "cat-mobile",
      developer: "Ubisoft",
      description: "Top up Growtopia resmi dan instan.",
      thumbnailUrl: "/images/games/growtopia.png",
      bannerUrl: "/images/banner/growtopia.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Growtopia." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-honkai-impact-3",
      name: "Honkai Impact 3",
      slug: "honkai-impact-3",
      categoryId: "cat-mobile",
      developer: "HoYoverse",
      description: "Top up Crystals Honkai Impact 3 resmi dan instan.",
      thumbnailUrl: "/images/games/honkai-impact-3.png",
      bannerUrl: "/images/banner/honkai-impact-3.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 801234567", helperText: "UID Honkai Impact 3." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-identity-v",
      name: "Identity V",
      slug: "identity-v",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Identity V resmi dan instan.",
      thumbnailUrl: "/images/games/identity-v.png",
      bannerUrl: "/images/banner/identity-v.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Identity V." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-infinite-borders",
      name: "Infinite Borders",
      slug: "infinite-borders",
      categoryId: "cat-mobile",
      developer: "Long Tech Network",
      description: "Top up Infinite Borders resmi dan instan.",
      thumbnailUrl: "/images/games/infinite-borders.png",
      bannerUrl: "/images/banner/infinite-borders.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Infinite Borders." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-king-of-avalon",
      name: "King of Avalon",
      slug: "king-of-avalon",
      categoryId: "cat-mobile",
      developer: "FunPlus",
      description: "Top up King of Avalon resmi dan instan.",
      thumbnailUrl: "/images/games/king-of-avalon.png",
      bannerUrl: "/images/banner/king-of-avalon.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID King of Avalon." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-lifeafter",
      name: "LifeAfter",
      slug: "lifeafter",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up LifeAfter resmi dan instan.",
      thumbnailUrl: "/images/games/life-after.png",
      bannerUrl: "/images/banner/life-after.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID LifeAfter." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-light-of-thel",
      name: "Light of Thel: New Era",
      slug: "light-of-thel",
      categoryId: "cat-mobile",
      developer: "iGAMES",
      description: "Top up Light of Thel: New Era resmi dan instan.",
      thumbnailUrl: "/images/games/light-of-thel.png",
      bannerUrl: "/images/banner/light-of-thel.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Light of Thel." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-lords-mobile",
      name: "Lords Mobile",
      slug: "lords-mobile",
      categoryId: "cat-mobile",
      developer: "IGG",
      description: "Top up Lords Mobile resmi dan instan.",
      thumbnailUrl: "/images/games/lords-mobile.png",
      bannerUrl: "/images/banner/lords-mobile.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Lords Mobile." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-love-and-deepspace",
      name: "Love and Deepspace",
      slug: "love-and-deepspace",
      categoryId: "cat-mobile",
      developer: "Papergames / Infold Games",
      description: "Top up Love and Deepspace resmi dan instan.",
      thumbnailUrl: "/images/games/love-and-deepspace.png",
      bannerUrl: "/images/banner/love-and-deepspace.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Love and Deepspace." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-magic-chess-go-go",
      name: "Magic Chess: Go Go",
      slug: "magic-chess-go-go",
      categoryId: "cat-mobile",
      developer: "Moonton",
      description: "Top up Magic Chess: Go Go resmi dan instan.",
      thumbnailUrl: "/images/games/magic-chess-go-go.png",
      bannerUrl: "/images/banner/magic-chess-go-go.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Magic Chess: Go Go." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-marvel-rivals",
      name: "Marvel Rivals",
      slug: "marvel-rivals",
      categoryId: "cat-pc",
      developer: "NetEase Games",
      description: "Top up Lattice Marvel Rivals resmi dan instan.",
      thumbnailUrl: "/images/games/marvel-rivals.png",
      bannerUrl: "/images/banner/marvel-rivals.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Marvel Rivals." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-metal-slug-awakening",
      name: "Metal Slug: Awakening",
      slug: "metal-slug-awakening",
      categoryId: "cat-mobile",
      developer: "Tencent Games / SNK",
      description: "Top up Metal Slug: Awakening resmi dan instan.",
      thumbnailUrl: "/images/games/metal-slug-awakening.png",
      bannerUrl: "/images/banner/metal-slug-awakening.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Metal Slug: Awakening." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-nba-infinite",
      name: "NBA Infinite",
      slug: "nba-infinite",
      categoryId: "cat-mobile",
      developer: "Tencent Games / 2K",
      description: "Top up NBA Infinite resmi dan instan.",
      thumbnailUrl: "/images/games/nba-infinite.png",
      bannerUrl: "/images/banner/nba-infinite.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID NBA Infinite." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-one-punch-man",
      name: "One Punch Man: The Strongest",
      slug: "one-punch-man",
      categoryId: "cat-mobile",
      developer: "Tencent Games",
      description: "Top up One Punch Man resmi dan instan.",
      thumbnailUrl: "/images/games/one-punch-man.png",
      bannerUrl: "/images/banner/one-punch-man.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID One Punch Man." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-point-blank",
      name: "Point Blank",
      slug: "point-blank",
      categoryId: "cat-pc",
      developer: "Zepetto",
      description: "Top up Cash Point Blank resmi dan instan.",
      thumbnailUrl: "/images/games/point-blank.png",
      bannerUrl: "/images/banner/point-blank.png",
      accountInputs: { userId: true, userLabel: "ID", userPlaceholder: "Contoh: 123456", helperText: "ID Point Blank Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ragnarok-x",
      name: "Ragnarok X: Next Generation",
      slug: "ragnarok-x",
      categoryId: "cat-mobile",
      developer: "Gravity",
      description: "Top up Ragnarok X: Next Generation resmi dan instan.",
      thumbnailUrl: "/images/games/rox.png",
      bannerUrl: "/images/banner/rox.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Ragnarok X." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ragnarok-m-eternal-love",
      name: "Ragnarok M: Eternal Love",
      slug: "ragnarok-m-eternal-love",
      categoryId: "cat-mobile",
      developer: "Gravity",
      description: "Top up Ragnarok M: Eternal Love resmi dan instan.",
      thumbnailUrl: "/images/games/rom.png",
      bannerUrl: "/images/banner/rom.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Ragnarok M." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-ragnarok-origin-classic",
      name: "Ragnarok Origin Classic",
      slug: "ragnarok-origin-classic",
      categoryId: "cat-mobile",
      developer: "Gravity",
      description: "Top up Ragnarok Origin Classic resmi dan instan.",
      thumbnailUrl: "/images/games/ragnarok-origin.png",
      bannerUrl: "/images/banner/ragnarok-origin.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Ragnarok Origin Classic." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-revelation-infinite-journey",
      name: "Revelation: Infinite Journey",
      slug: "revelation-infinite-journey",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Revelation: Infinite Journey resmi dan instan.",
      thumbnailUrl: "/images/games/revelation-infinite-journey.png",
      bannerUrl: "/images/banner/revelation-infinite-journey.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Revelation." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-rush-royale",
      name: "Rush Royale",
      slug: "rush-royale",
      categoryId: "cat-mobile",
      developer: "Vizor Games",
      description: "Top up Rush Royale resmi dan instan.",
      thumbnailUrl: "/images/games/rush-royale.png",
      bannerUrl: "/images/banner/rush-royale.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Rush Royale." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-sausage-man",
      name: "Sausage Man",
      slug: "sausage-man",
      categoryId: "cat-mobile",
      developer: "XD Entertainment",
      description: "Top up Sausage Man resmi dan instan.",
      thumbnailUrl: "/images/games/sausage-man.png",
      bannerUrl: "/images/banner/sausage-man.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Sausage Man." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-state-of-survival",
      name: "State of Survival: Zombie War",
      slug: "state-of-survival",
      categoryId: "cat-mobile",
      developer: "KingsGroup / FunPlus",
      description: "Top up State of Survival resmi dan instan.",
      thumbnailUrl: "/images/games/state-of-survival.png",
      bannerUrl: "/images/banner/state-of-survival.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID State of Survival." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-super-sus",
      name: "Super Sus",
      slug: "super-sus",
      categoryId: "cat-mobile",
      developer: "SPACESHIP Studio",
      description: "Top up Super Sus resmi dan instan.",
      thumbnailUrl: "/images/games/super-sus.png",
      bannerUrl: "/images/banner/super-sus.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Super Sus." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-tom-and-jerry-chase",
      name: "Tom and Jerry: Chase",
      slug: "tom-and-jerry-chase",
      categoryId: "cat-mobile",
      developer: "NetEase Games",
      description: "Top up Tom and Jerry: Chase resmi dan instan.",
      thumbnailUrl: "/images/games/tom-and-jerry-chase.png",
      bannerUrl: "/images/banner/tom-and-jerry-chase.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Tom and Jerry: Chase." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-war-robots",
      name: "War Robots",
      slug: "war-robots",
      categoryId: "cat-mobile",
      developer: "Pixonic",
      description: "Top up War Robots resmi dan instan.",
      thumbnailUrl: "/images/games/war-robots.png",
      bannerUrl: "/images/banner/war-robots.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID War Robots." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-watcher-of-realms",
      name: "Watcher of Realms",
      slug: "watcher-of-realms",
      categoryId: "cat-mobile",
      developer: "Moonton",
      description: "Top up Watcher of Realms resmi dan instan.",
      thumbnailUrl: "/images/games/watcher-of-realms.png",
      bannerUrl: "/images/banner/watcher-of-realms.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Watcher of Realms." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-whiteout-survival",
      name: "Whiteout Survival",
      slug: "whiteout-survival",
      categoryId: "cat-mobile",
      developer: "Century Games",
      description: "Top up Whiteout Survival resmi dan instan.",
      thumbnailUrl: "/images/games/whiteout-survival.png",
      bannerUrl: "/images/banner/whiteout-survival.png",
      accountInputs: { userId: true, userLabel: "UID", userPlaceholder: "Contoh: 123456", helperText: "UID Whiteout Survival." },
      hasServerCheck: true,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-likee",
      name: "Likee",
      slug: "likee",
      categoryId: "cat-app",
      developer: "BIGO Technology",
      description: "Top up Likee Beans resmi dan instan.",
      thumbnailUrl: "/images/games/likee.png",
      bannerUrl: "/images/banner/likee.png",
      accountInputs: { userId: true, userLabel: "User ID", userPlaceholder: "Contoh: 123456", helperText: "User ID Likee Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-lita",
      name: "Lita",
      slug: "lita",
      categoryId: "cat-app",
      developer: "Lita",
      description: "Top up Lita Beans resmi dan instan.",
      thumbnailUrl: "/images/games/lita.png",
      bannerUrl: "/images/banner/lita.png",
      accountInputs: { userId: true, userLabel: "User ID", userPlaceholder: "Contoh: 123456", helperText: "User ID Lita Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-zepeto",
      name: "Zepeto",
      slug: "zepeto",
      categoryId: "cat-app",
      developer: "Naver Z",
      description: "Top up Zepeto ZEM resmi dan instan.",
      thumbnailUrl: "/images/games/zepeto.png",
      bannerUrl: "/images/banner/zepeto.png",
      accountInputs: { userId: true, userLabel: "User ID", userPlaceholder: "Contoh: 123456", helperText: "User ID Zepeto Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-garena-shell",
      name: "Garena Shell",
      slug: "garena-shell",
      categoryId: "cat-voucher",
      developer: "Garena",
      description: "Beli Voucher Garena Shell resmi untuk Free Fire, CODM, dan game Garena lainnya.",
      thumbnailUrl: "/images/games/garena-shell.png",
      bannerUrl: "/images/banner/garena-shell.png",
      accountInputs: { userId: true, userLabel: "Garena UID", userPlaceholder: "Contoh: 123456", helperText: "UID Garena Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-megaxus-voucher",
      name: "Megaxus Voucher",
      slug: "megaxus-voucher",
      categoryId: "cat-voucher",
      developer: "Megaxus",
      description: "Beli Voucher Megaxus resmi untuk game Megaxus.",
      thumbnailUrl: "/images/games/megaxus-voucher.png",
      bannerUrl: "/images/banner/megaxus-voucher.png",
      accountInputs: { userId: true, userLabel: "ID", userPlaceholder: "Contoh: 123456", helperText: "ID Megaxus Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-pb-zepetto-voucher",
      name: "Point Blank Zepetto Voucher",
      slug: "pb-zepetto-voucher",
      categoryId: "cat-voucher",
      developer: "Zepetto",
      description: "Beli Voucher Point Blank Zepetto resmi.",
      thumbnailUrl: "/images/games/pb-zepetto-voucher.png",
      bannerUrl: "/images/banner/pb-zepetto-voucher.png",
      accountInputs: { userId: true, userLabel: "ID", userPlaceholder: "Contoh: 123456", helperText: "ID Point Blank Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-psn-voucher",
      name: "PlayStation Network Card",
      slug: "psn-voucher",
      categoryId: "cat-voucher",
      developer: "Sony Interactive Entertainment",
      description: "Beli Voucher PlayStation Network Card resmi.",
      thumbnailUrl: "/images/games/psn-voucher.png",
      bannerUrl: "/images/banner/psn-voucher.png",
      accountInputs: { userId: true, userLabel: "Email PSN", userPlaceholder: "Contoh: email@example.com", helperText: "Email akun PSN Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
    {
      id: "game-razer-gold",
      name: "Razer Gold",
      slug: "razer-gold",
      categoryId: "cat-voucher",
      developer: "Razer",
      description: "Beli Voucher Razer Gold resmi untuk game dan hiburan Razer.",
      thumbnailUrl: "/images/games/razer-gold.png",
      bannerUrl: "/images/banner/razer-gold.png",
      accountInputs: { userId: true, userLabel: "Email Razer", userPlaceholder: "Contoh: email@example.com", helperText: "Email akun Razer Gold Anda." },
      hasServerCheck: false,
      isPopular: false,
      isActive: true,
      createdAt: new Date(),
    },
];

export const initialItems: Item[] = [
  // Mobile Legends
  { id: "item-ml-wdp", gameId: "game-mlbb", name: "Weekly Diamond Pass", code: "ML_WDP", price: 27500, originalPrice: 32000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_wdp_icon.png", isPromo: true, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-ml-86", gameId: "game-mlbb", name: "86 Diamonds (78 + 8 Bonus)", code: "ML_86", price: 21500, originalPrice: 24000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_86_icon.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-ml-172", gameId: "game-mlbb", name: "172 Diamonds (156 + 16 Bonus)", code: "ML_172", price: 42500, originalPrice: 48000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_172_icon.png", isPromo: false, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-ml-257", gameId: "game-mlbb", name: "257 Diamonds (234 + 23 Bonus)", code: "ML_257", price: 63500, originalPrice: 72000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_257_icon.png", isPromo: true, sortOrder: 4, isActive: true, createdAt: new Date() },
  { id: "item-ml-706", gameId: "game-mlbb", name: "706 Diamonds (625 + 81 Bonus)", code: "ML_706", price: 172000, originalPrice: 195000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_706_icon.png", isPromo: false, sortOrder: 5, isActive: true, createdAt: new Date() },
  { id: "item-ml-2195", gameId: "game-mlbb", name: "2195 Diamonds (1860 + 335 Bonus)", code: "ML_2195", price: 519000, originalPrice: 580000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_2195_icon.png", isPromo: false, sortOrder: 6, isActive: true, createdAt: new Date() },
  { id: "item-ml-twilight", gameId: "game-mlbb", name: "Twilight Pass", code: "ML_TWILIGHT", price: 145000, originalPrice: 160000, iconUrl: "https://wacdn.mlbb.com/image/mlbb_twilight_icon.png", isPromo: false, sortOrder: 7, isActive: true, createdAt: new Date() },

  // Free Fire
  { id: "item-ff-70", gameId: "game-ff", name: "70 Diamonds", code: "FF_70", price: 9500, originalPrice: 12000, iconUrl: "https://d1j1u4tjg8uq8g.cloudfront.net/ff_70_icon.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-ff-140", gameId: "game-ff", name: "140 Diamonds", code: "FF_140", price: 19000, originalPrice: 22000, iconUrl: "https://d1j1u4tjg8uq8g.cloudfront.net/ff_140_icon.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-ff-355", gameId: "game-ff", name: "355 Diamonds", code: "FF_355", price: 47000, originalPrice: 55000, iconUrl: "https://d1j1u4tjg8uq8g.cloudfront.net/ff_355_icon.png", isPromo: true, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-ff-720", gameId: "game-ff", name: "720 Diamonds", code: "FF_720", price: 94000, originalPrice: 110000, iconUrl: "https://d1j1u4tjg8uq8g.cloudfront.net/ff_720_icon.png", isPromo: false, sortOrder: 4, isActive: true, createdAt: new Date() },
  { id: "item-ff-member-week", gameId: "game-ff", name: "Membership Mingguan", code: "FF_MWEEK", price: 29000, originalPrice: 35000, iconUrl: "https://d1j1u4tjg8uq8g.cloudfront.net/ff_member_icon.png", isPromo: true, sortOrder: 5, isActive: true, createdAt: new Date() },

  // Genshin Impact
  { id: "item-gi-welkin", gameId: "game-genshin", name: "Blessing of the Welkin Moon", code: "GI_WELKIN", price: 79000, originalPrice: 85000, iconUrl: "https://webstatic.mihoyo.com/icon/Genshin_Welkin_Moon.png", isPromo: true, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-gi-60", gameId: "game-genshin", name: "60 Genesis Crystals", code: "GI_60", price: 15500, originalPrice: 18000, iconUrl: "https://webstatic.mihoyo.com/icon/Genshin_60_Crystals.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-gi-300", gameId: "game-genshin", name: "300 + 30 Genesis Crystals", code: "GI_300", price: 74000, originalPrice: 82000, iconUrl: "https://webstatic.mihoyo.com/icon/Genshin_300_Crystals.png", isPromo: false, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-gi-980", gameId: "game-genshin", name: "980 + 110 Genesis Crystals", code: "GI_980", price: 235000, originalPrice: 260000, iconUrl: "https://webstatic.mihoyo.com/icon/Genshin_980_Crystals.png", isPromo: false, sortOrder: 4, isActive: true, createdAt: new Date() },
  { id: "item-gi-1980", gameId: "game-genshin", name: "1980 + 260 Genesis Crystals", code: "GI_1980", price: 470000, originalPrice: 510000, iconUrl: "https://webstatic.mihoyo.com/icon/Genshin_1980_Crystals.png", isPromo: false, sortOrder: 5, isActive: true, createdAt: new Date() },

  // Valorant
  { id: "item-val-475", gameId: "game-valorant", name: "475 Valorant Points", code: "VAL_475", price: 54000, originalPrice: 60000, iconUrl: "https://media.valorantpoint.com/icon/valorant_points_475.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-val-1000", gameId: "game-valorant", name: "1000 Valorant Points", code: "VAL_1000", price: 108000, originalPrice: 120000, iconUrl: "https://media.valorantpoint.com/icon/valorant_points_1000.png", isPromo: true, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-val-2050", gameId: "game-valorant", name: "2050 Valorant Points", code: "VAL_2050", price: 215000, originalPrice: 240000, iconUrl: "https://media.valorantpoint.com/icon/valorant_points_2050.png", isPromo: false, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-val-3650", gameId: "game-valorant", name: "3650 Valorant Points", code: "VAL_3650", price: 375000, originalPrice: 420000, iconUrl: "https://media.valorantpoint.com/icon/valorant_points_3650.png", isPromo: false, sortOrder: 4, isActive: true, createdAt: new Date() },

  // Wild Rift
  { id: "item-lol-100", gameId: "game-lol-wr", name: "100 Wild Cores", code: "LOL_100", price: 25000, originalPrice: 28000, iconUrl: "https://media.valorantpoint.com/icon/wild_cores_100.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-lol-500", gameId: "game-lol-wr", name: "500 Wild Cores", code: "LOL_500", price: 115000, originalPrice: 130000, iconUrl: "https://media.valorantpoint.com/icon/wild_cores_500.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-lol-1000", gameId: "game-lol-wr", name: "1,000 Wild Cores", code: "LOL_1000", price: 220000, originalPrice: 240000, iconUrl: "https://media.valorantpoint.com/icon/wild_cores_1000.png", isPromo: true, sortOrder: 3, isActive: true, createdAt: new Date() },

  // PUBG Mobile
  { id: "item-pubg-60", gameId: "game-pubgm", name: "60 UC", code: "PUBG_60", price: 14000, originalPrice: 16000, iconUrl: "https://static.pubg.com/icon/pubg_uc_60.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-pubg-325", gameId: "game-pubgm", name: "325 UC", code: "PUBG_325", price: 69000, originalPrice: 77000, iconUrl: "https://static.pubg.com/icon/pubg_uc_325.png", isPromo: true, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-pubg-660", gameId: "game-pubgm", name: "660 UC", code: "PUBG_660", price: 139000, originalPrice: 155000, iconUrl: "https://static.pubg.com/icon/pubg_uc_660.png", isPromo: false, sortOrder: 3, isActive: true, createdAt: new Date() },

  // Call of Duty Mobile
  { id: "item-codm-80", gameId: "game-codm", name: "80 Call of Duty Points", code: "CODM_80", price: 12000, originalPrice: 14000, iconUrl: "https://media.valorantpoint.com/icon/codm_80_points.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-codm-420", gameId: "game-codm", name: "420 Call of Duty Points", code: "CODM_420", price: 62000, originalPrice: 70000, iconUrl: "https://media.valorantpoint.com/icon/codm_420_points.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-codm-840", gameId: "game-codm", name: "840 Call of Duty Points", code: "CODM_840", price: 125000, originalPrice: 140000, iconUrl: "https://media.valorantpoint.com/icon/codm_840_points.png", isPromo: true, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-codm-1680", gameId: "game-codm", name: "1,680 Call of Duty Points", code: "CODM_1680", price: 249000, originalPrice: 280000, iconUrl: "https://media.valorantpoint.com/icon/codm_1680_points.png", isPromo: false, sortOrder: 4, isActive: true, createdAt: new Date() },
  { id: "item-codm-4200", gameId: "game-codm", name: "4,200 Call of Duty Points", code: "CODM_4200", price: 620000, originalPrice: 690000, iconUrl: "https://media.valorantpoint.com/icon/codm_4200_points.png", isPromo: true, sortOrder: 5, isActive: true, createdAt: new Date() },

  // Roblox
  { id: "item-rob-100", gameId: "game-roblox", name: "100 Robux", code: "ROB_100", price: 15000, originalPrice: 18000, iconUrl: "https://shared.fastly.steamstatic.com/icon/roblox_100_robux.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-rob-500", gameId: "game-roblox", name: "500 Robux", code: "ROB_500", price: 75000, originalPrice: 85000, iconUrl: "https://shared.fastly.steamstatic.com/icon/roblox_500_robux.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-rob-1000", gameId: "game-roblox", name: "1,000 Robux", code: "ROB_1000", price: 149000, originalPrice: 168000, iconUrl: "https://shared.fastly.steamstatic.com/icon/roblox_1000_robux.png", isPromo: true, sortOrder: 3, isActive: true, createdAt: new Date() },
  { id: "item-rob-2200", gameId: "game-roblox", name: "2,200 Robux", code: "ROB_2200", price: 329000, originalPrice: 368000, iconUrl: "https://shared.fastly.steamstatic.com/icon/roblox_2200_robux.png", isPromo: false, sortOrder: 4, isActive: true, createdAt: new Date() },


  // PUBG New State
  { id: "item-pubg_ns_60", gameId: "game-pubg-ns", name: "PUBG NS 60 UC", code: "PUBG_NS_60", price: 14000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-pubg_ns_325", gameId: "game-pubg-ns", name: "PUBG NS 325 UC", code: "PUBG_NS_325", price: 69000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: true, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-pubg_ns_660", gameId: "game-pubg-ns", name: "PUBG NS 660 UC", code: "PUBG_NS_660", price: 139000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 3, isActive: true, createdAt: new Date() },
  // Honor of Kings
  { id: "item-hok_100", gameId: "game-hok", name: "Honor of Kings 100 Token", code: "HOK_100", price: 15000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-hok_500", gameId: "game-hok", name: "Honor of Kings 500 Token", code: "HOK_500", price: 72000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  // Honkai Star Rail
  { id: "item-hsr_60", gameId: "game-honkai", name: "Honkai Star Rail 60 Crystals", code: "HSR_60", price: 15500, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-hsr_300", gameId: "game-honkai", name: "Honkai Star Rail 300 Crystals", code: "HSR_300", price: 74000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  // Zenless Zone Zero
  { id: "item-zzz_60", gameId: "game-zenless", name: "Zenless Zone Zero 60 Crystals", code: "ZZZ_60", price: 15500, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-zzz_300", gameId: "game-zenless", name: "Zenless Zone Zero 300 Crystals", code: "ZZZ_300", price: 74000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  // Delta Force
  { id: "item-delta_100", gameId: "game-delta", name: "Delta Force 100 Coins", code: "DELTA_100", price: 15000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-delta_500", gameId: "game-delta", name: "Delta Force 500 Coins", code: "DELTA_500", price: 72000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  // AFK Journey
  { id: "item-afk_60", gameId: "game-afk-journey", name: "AFK Journey 60 Crystals", code: "AFK_60", price: 15500, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-afk_300", gameId: "game-afk-journey", name: "AFK Journey 300 Crystals", code: "AFK_300", price: 74000, originalPrice: null, iconUrl: "https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/753/header.jpg", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },

  // Steam Wallet
  { id: "item-steam-45k", gameId: "game-steam", name: "Steam Wallet IDR 45.000", code: "STEAM_45K", price: 47500, originalPrice: 50000, iconUrl: "https://shared.fastly.steamstatic.com/icon/steam_wallet_45k.png", isPromo: false, sortOrder: 1, isActive: true, createdAt: new Date() },
  { id: "item-steam-90k", gameId: "game-steam", name: "Steam Wallet IDR 90.000", code: "STEAM_90K", price: 94000, originalPrice: 100000, iconUrl: "https://shared.fastly.steamstatic.com/icon/steam_wallet_90k.png", isPromo: false, sortOrder: 2, isActive: true, createdAt: new Date() },
  { id: "item-steam-250k", gameId: "game-steam", name: "Steam Wallet IDR 250.000", code: "STEAM_250K", price: 259000, originalPrice: 275000, iconUrl: "https://shared.fastly.steamstatic.com/icon/steam_wallet_250k.png", isPromo: true, sortOrder: 3, isActive: true, createdAt: new Date() },
];

export const initialPaymentMethods: PaymentMethod[] = [
  {
    id: "pay-dana",
    code: "DANA",
    name: "DANA",
    type: "EWALLET",
    feeFlat: 1000,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Logo_dana_blue.svg",
    accountNumber: "081234567890",
    instructions: [
      "Buka aplikasi DANA di smartphone Anda.",
      "Lakukan transfer ke nomor Virtual Akun/Merchant DANA yang tertera.",
      "Konfirmasi nominal pembayaran dan masukkan PIN DANA Anda.",
      "Pesanan akan diproses otomatis begitu pembayaran diterima.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "pay-gopay",
    code: "GOPAY",
    name: "GoPay",
    type: "EWALLET",
    feeFlat: 1000,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/6/65/Gopay_logo_%282019%29.svg",
    accountNumber: "081234567890",
    instructions: [
      "Buka aplikasi Gojek / GoPay.",
      "Klik Bayar dan scan kode atau transfer ke merchant RXR.",
      "Pastikan saldo mencukupi dan selesaikan pembayaran dengan PIN.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "pay-bca-va",
    code: "BCA_VA",
    name: "BCA Virtual Account",
    type: "VA",
    feeFlat: 2500,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Bank_Central_Asia.svg",
    accountNumber: "8077708123456789",
    instructions: [
      "Buka BCA mobile (m-BCA) atau KlikBCA.",
      "Pilih menu m-Transfer > BCA Virtual Account.",
      "Masukkan nomor Virtual Account yang tertera pada invoice.",
      "Periksa rincian pembayaran, lalu masukkan PIN m-BCA Anda.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "pay-mandiri-va",
    code: "MANDIRI_VA",
    name: "Mandiri Virtual Account",
    type: "VA",
    feeFlat: 2500,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Bank_Mandiri_logo_2016.svg",
    accountNumber: "8890808123456789",
    instructions: [
      "Buka aplikasi Livin' by Mandiri.",
      "Pilih menu Bayar > Multi Payment.",
      "Pilih penyedia jasa atau masukkan Kode Perusahaan / VA.",
      "Konfirmasi transaksi dan masukkan PIN Livin'.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "pay-bri-va",
    code: "BRI_VA",
    name: "BRI Virtual Account (BRIVA)",
    type: "VA",
    feeFlat: 2500,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/2/2e/BRI_2020.svg",
    accountNumber: "1280008123456789",
    instructions: [
      "Buka aplikasi BRImo.",
      "Pilih menu Pembayaran > BRIVA.",
      "Masukkan nomor BRIVA yang tertera pada invoice.",
      "Periksa tagihan dan masukkan PIN BRImo.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "pay-alfamart",
    code: "ALFAMART",
    name: "Alfamart / Alfamidi",
    type: "RETAIL",
    feeFlat: 3500,
    feePercentage: "0.00",
    iconUrl: "https://upload.wikimedia.org/wikipedia/commons/8/86/Alfamart_logo.svg",
    accountNumber: "ALFA-901823719",
    instructions: [
      "Kunjungi gerai Alfamart terdekat.",
      "Sampaikan kepada kasir ingin melakukan pembayaran tagihan merchant 'RXR'.",
      "Tunjukkan kode pembayaran yang tertera pada invoice.",
      "Bayar sesuai nominal ke kasir dan simpan struk pembayaran.",
    ],
    isActive: true,
    createdAt: new Date(),
  },
];

export const initialPromoCodes: PromoCode[] = [
  {
    id: "promo-1",
    code: "RXRHEMAT",
    discountType: "PERCENTAGE",
    discountValue: 10,
    maxDiscount: 15000,
    minPurchase: 20000,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "promo-2",
    code: "NEONBARU",
    discountType: "FLAT",
    discountValue: 5000,
    maxDiscount: 5000,
    minPurchase: 25000,
    isActive: true,
    createdAt: new Date(),
  },
  {
    id: "promo-3",
    code: "SULTANVIP",
    discountType: "PERCENTAGE",
    discountValue: 15,
    maxDiscount: 30000,
    minPurchase: 100000,
    isActive: true,
    createdAt: new Date(),
  },
];

import fs from "fs";
import path from "path";

const DATA_DIR = path.join(process.cwd(), ".data");
const TX_FILE = path.join(DATA_DIR, "transactions.json");

const sampleTransactions: Transaction[] = [
  {
    id: "tx-sample-1",
    invoiceNumber: "TPY-SAMPLE-001",
    gameId: "game-mlbb",
    gameName: "Mobile Legends: Bang Bang",
    itemId: "item-ml-86",
    itemName: "86 Diamonds (78 + 8 Bonus)",
    paymentMethodId: "pay-qris",
    paymentMethodName: "QRIS Realtime",
    accountData: { userId: "12345678", zoneId: "2105", nickname: "Mythic_Slayer99" },
    customerPhone: "081234567890",
    customerEmail: "gamer@example.com",
    subtotal: 21500,
    fee: 151,
    discount: 2150,
    totalAmount: 19501,
    status: "SUCCESS",
    paymentDetails: {
      qrString: "0002010102122658...",
      expiredAt: new Date(Date.now() + 86400000).toISOString(),
      paidAt: new Date().toISOString(),
    },
    notes: "Transaksi sukses via QRIS",
    createdAt: new Date(Date.now() - 3600000),
    updatedAt: new Date(Date.now() - 3500000),
  },
];

// In-memory runtime store with file persistence for demo mode
export class MemoryStore {
  static categories: Category[] = [...initialCategories];
  static games: Game[] = [...initialGames];
  static items: Item[] = [...initialItems];
  static paymentMethods: PaymentMethod[] = [...initialPaymentMethods];
  static promoCodes: PromoCode[] = [...initialPromoCodes];

  static getTransactions(): Transaction[] {
    try {
      if (typeof window === "undefined" && fs.existsSync(TX_FILE)) {
        const raw = fs.readFileSync(TX_FILE, "utf-8");
        return JSON.parse(raw);
      }
    } catch {
      // ignore
    }
    return sampleTransactions;
  }

  static saveTransaction(tx: Transaction) {
    const list = this.getTransactions();
    const existingIndex = list.findIndex(
      (t) => t.invoiceNumber.toUpperCase() === tx.invoiceNumber.toUpperCase()
    );
    if (existingIndex >= 0) {
      list[existingIndex] = tx;
    } else {
      list.unshift(tx);
    }
    try {
      if (typeof window === "undefined") {
        if (!fs.existsSync(DATA_DIR)) {
          fs.mkdirSync(DATA_DIR, { recursive: true });
        }
        fs.writeFileSync(TX_FILE, JSON.stringify(list, null, 2), "utf-8");
      }
    } catch {
      // ignore
    }
  }
}
